# Numpy 패키지
- pandas에서 데이터를 저장 및 처리에 사용되는 패키지

- 외부 패키지로 반드시 설치 필요

- 고속 데이터 러이, 수치 계한 수행 패키지 

- 머신러닝, 답러팅 패키지Scikit-lern, Tensorflow, pyTorch 등등에서도 사용

- [중요] 동일한 데이터 타입의 데이터를 저장하는 배열 타입

In [132]:
import pandas as pd
import numpy as np

## ndarray 객체 생성 하기 => numpy.array()

In [133]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [134]:
type(arr1)

numpy.ndarray

## ndarray 객체의 속성 
- 객체변수명.속성명
- ndim 차원
- shape 형태
- dtype 타입
- itemsize 배열 요소의 바이트크기
- item 배열 요소의 갯수

In [135]:
print(arr1.ndim, arr1.shape, arr1.dtype, arr1.itemsize, arr1.size,sep='\n')

1
(3,)
int32
4
3


## 배열의 요소 인덱싱
- ZeroBase 인덱스 자동 지정

In [136]:
print(f'객체변수명 arr1 : {arr1}')
print(f'객체변수명 arr1[0] : {arr1[0]}')
print(f'객체변수명 arr1[1] : {arr1[1]}')

객체변수명 arr1 : [1 2 3]
객체변수명 arr1[0] : 1
객체변수명 arr1[1] : 2


## numpy.ones()
- 모든 값을 1으로 채워서 ndarray 객채 생성 함수

In [137]:
# arr2 = np.array([1, 1, 1, 1])
arr2 = np.ones(4, dtype=np.int16)
arr2

array([1, 1, 1, 1], dtype=int16)

In [138]:
print(arr2.ndim, arr2.shape, arr2.dtype, arr2.itemsize, arr2.size,sep='\n')

1
(4,)
int16
2
4


## numpy.empty()
- 초기화하지 않고 ndarray 생성 => numpy.empty

In [139]:
arr3 = np.empty((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [140]:
# 2차원 형태의 ndarray 객체 생성
myArr1 = np.ones((3,6), dtype=np.int16)
myArr1

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

In [141]:
print(myArr1.ndim, myArr1.shape, myArr1.dtype, myArr1.itemsize, myArr1.size,sep='\n')

2
(3, 6)
int16
2
18


## flatten : 2차원 -> 1차원 변경

In [142]:
myArr2 = myArr1.flatten()
myArr2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

## reshape : 1차원 -> 2차원 변경

In [143]:
myArr2.reshape(2,9)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [144]:
myArr2.reshape((2,3,3))

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [145]:
myArr2.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

## reshape(-1, n), reshape(n, -1) : 차원, 형태변환
- 알아서 나누는 값 : -1

In [146]:
dd = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [147]:
dd.reshape((-1,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [148]:
dd.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])