# 연속형자료형 => 범주형 전환
- pandas cut() 함수 제공
    - PARAMETOR [기본값], a < value <= b
        - bins : 구간 갯수                              -> 정렬 후 지정된 갯수 만큼 구간
        - right : 오른쪽 값 포함여부                    -> True
        - labels : 구간에 대한 라벨, 리스트             -> 구간 갯수에 맞게 설정
        - include_lowest : 왼쪽의 가장 작은값 포함 여부 -> False
        - retbins : 구간리스트 반환 여부                -> False
    - RESULT
        - 범주형 변환 데이터
        - 구간 리스트 <- retbins = True 로 설정된 경우 반환


In [23]:
import pandas as pd

# df 생성
df = pd.DataFrame({'value': [1,2,3,4,5]})
df

value
0      1
1      2
2      3
3      4
4      5

In [24]:
# 연속형 자료형 -> 범주형 (category) 변환
# [기본값] right = True, include_lowest = False
caDF, retbins = pd.cut(df['value'], bins=2, retbins=True)
caDF

0    (0.996, 3.0]
1    (0.996, 3.0]
2    (0.996, 3.0]
3      (3.0, 5.0]
4      (3.0, 5.0]
Name: value, dtype: category
Categories (2, interval[float64, right]): [(0.996, 3.0] < (3.0, 5.0]]

In [25]:
retbins

array([0.996, 3.   , 5.   ])

In [26]:
caDF, retbins = pd.cut(df['value'], bins=2, retbins=True, include_lowest=True)
caDF

0    (0.995, 3.0]
1    (0.995, 3.0]
2    (0.995, 3.0]
3      (3.0, 5.0]
4      (3.0, 5.0]
Name: value, dtype: category
Categories (2, interval[float64, right]): [(0.995, 3.0] < (3.0, 5.0]]

In [27]:
retbins

array([0.996, 3.   , 5.   ])

In [28]:
caDF, retbins = pd.cut(df['value'], bins=2, retbins=True, right=False)
caDF

0      [1.0, 3.0)
1      [1.0, 3.0)
2    [3.0, 5.004)
3    [3.0, 5.004)
4    [3.0, 5.004)
Name: value, dtype: category
Categories (2, interval[float64, left]): [[1.0, 3.0) < [3.0, 5.004)]

In [29]:
retbins

array([1.   , 3.   , 5.004])