# PyTorch
---

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.12.1+cu113'

## [1] Tensor 생성
---

In [4]:
# [기본] tensor(data)
t1 = torch.tensor([1, 2, 3], dtype=torch.int32)

type(t1), t1.shape, t1.dtype, t1.device

(torch.Tensor, torch.Size([3]), torch.int32, device(type='cpu'))

In [5]:
# 데이터 타입은 큰 타입으로 통일 -> 손실 방지
t2 = torch.tensor([1., 2, 3])

type(t2), t2.shape, t2.dtype, t2.device

(torch.Tensor, torch.Size([3]), torch.float32, device(type='cpu'))

In [6]:
t3 = torch.tensor([[1., 2, 3], [1, 2, 2]])

type(t3), t3.shape, t3.dtype, t3.device

(torch.Tensor, torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [7]:
t4 = torch.zeros(size=(10, 3))
t4

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
t5 = torch.ones_like(t4)
t5

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
t6 = torch.rand_like(t5)
t6

tensor([[0.9188, 0.4657, 0.6284],
        [0.9887, 0.5245, 0.7580],
        [0.1069, 0.5138, 0.2008],
        [0.7613, 0.9538, 0.5408],
        [0.6931, 0.7376, 0.1033],
        [0.1429, 0.5143, 0.4437],
        [0.4504, 0.2650, 0.6950],
        [0.0531, 0.0899, 0.9101],
        [0.5252, 0.1008, 0.9987],
        [0.4166, 0.0853, 0.6195]])

In [19]:
# GPU 활용
torch.cuda.is_available()

True

## [2] Indexing & Slicing
---

In [11]:
t3

tensor([[1., 2., 3.],
        [1., 2., 2.]])

In [12]:
# 행 -> [행인덱스]
t3[0]

tensor([1., 2., 3.])

In [13]:
t3[1]

tensor([1., 2., 2.])

In [14]:
# 열 -> [행, 열]
t3[:, 0]

tensor([1., 1.])

In [15]:
 t3.add_(5)

tensor([[6., 7., 8.],
        [6., 7., 7.]])

In [16]:
# 넘파이로 바꾸기
# 같은 메모리를 공유중이기에 변경시 같이 적용
tn = t3.numpy()

In [17]:
t3.add_(1000)

tensor([[1006., 1007., 1008.],
        [1006., 1007., 1007.]])

In [18]:
tn

array([[1006., 1007., 1008.],
       [1006., 1007., 1007.]], dtype=float32)